remote_theme: just-the-docs/just-the-docs
title: AnyPackage
description: A PowerShell universal package manager.
permalink: /:categories/:title
aux_links:
  "GitHub":
    - "https://github.com/AnyPackage/AnyPackage"

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/AnyPackage/AnyPackage-Docs"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "<a rel=\"license\" href=\"http://creativecommons.org/licenses/by/4.0/\"><img alt=\"Creative Commons License\" style=\"border-width:0\" src=\"https://i.creativecommons.org/l/by/4.0/88x31.png\" /></a><br />This work is licensed under a <a rel=\"license\" href=\"http://creativecommons.org/licenses/by/4.0/\">Creative Commons Attribution 4.0 International License</a>.<br />Copyright &copy; 2023 Thomas Nieto - All rights reserved."